name: dart_application_1
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.0

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  socket_io_client: ^1.0.2
  shelf: ^1.2.0
  shelf_web_socket: ^2.0.0
  socket_io: ^1.0.1
  socket_io_common: ^1.0.1
  process: ^4.2.4
  dart_console: ^1.0.0
  crypto: ^3.0.1
  

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0 
